# Generated by Django 5.2.3 on 2025-07-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_rchat", "0002_alter_groupmessage_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatgroup",
            old_name="group_name",
            new_name="name",
        ),
    ]
